### ISSUE TITLE
Raven not writing anything

### ISSUE THREAD

**Issue by dcopetti** [lbcb-sci/raven#10]
Hello,
I wonder if, for large and complex genomes, it would be better to have Raven writing some intermediate files, that could be used to resume the run.
In my case, my job was running for more than 2 weeks when it died for memory limitation. It would have been nice to restart the process with new resources (e.g. less CPUs and more memory, then switching back to more CPUs) and use better the computing resources we have available.
I agree that for small genomes this is not an issue, but with mammalian and large plant genomes, time and costs start becoming relevant.
Any thoughts to go in this direction?

Dario

**Comment by rvaser** [comment]
Hi Dario,
I get your point, I know how frustrating it is. A human genome run got killed two times due to power outage. I think an option which saves intermediate files for job resuming is doable, will put it on a to-do list.

Best regards,
Robert

**Comment by rvaser** [comment]
@dcopetti, I have implemented a resume option in version `1.1.4`.
