### ISSUE TITLE
[raven::] error: file 

### ISSUE THREAD

**Issue by Tdanis** [lbcb-sci/raven#11]
Hi, so this is my command : 
raven -p 3 - t 20 /my path to file/my-file.fastq

and the output error.

[raven::] error: file - has unsupported format extension (valid extensions: .fasta, .fasta.gz, .fa, .fa.gz, .fastq, .fastq.gz, .fq, .fq.gz)!

Could you help me please?

**Comment by rvaser** [comment]
Hello,
can you paste the exact command you used?

Best regards,
Robert

**Comment by rvaser** [comment]
The problem is that you typed `- t` instead of `-t`. `-` is picked up as the floating parameter instead of the fastq file. That was a tricky one!

**Comment by Tdanis** [comment]
Sorry about that 

Thank you
