### ISSUE TITLE
No fasta output

### ISSUE THREAD

**Issue by Tdanis** [lbcb-sci/raven#12]
Another issue it is that with command, 

raven -p 3 -t 20 /home/Porechop/porechoped.fastq  > contigs.fasta

contigs.fasta is an empty file 
and the ouput is this,
[raven.txt](https://github.com/lbcb-sci/raven/files/3768098/raven.txt)

any solution-suggestion for this?

Thank you very much

**Comment by rvaser** [comment]
Did the run even finish? The log you have sent me stops abruptly. Was there any error message?

Best regards,
Robert

**Comment by Tdanis** [comment]
No no nothing , just this . 
Any suggestion?

**Comment by rvaser** [comment]
That is quite weird. Try running with only two polishing iterations.

**Comment by Tdanis** [comment]
It works only with 2 rounds of Racon

**Comment by rvaser** [comment]
No idea what could be wrong with the third round :) Do you mind sharing the data via mail?

**Comment by Tdanis** [comment]
The project is still in progress and we can not share yet our data.
Thank you very much for your help.

Θεόδωρος Δανης
Thodoris Danis

________________________________

**Comment by rvaser** [comment]
I understand. You can try running the third iteration directly with Racon and see if it finishes. Or if you have a different set, try Raven with 3 polishing iterations on it.

**Comment by Tdanis** [comment]
Ok ok I will try Raven with a smaller dataset.
Is there ant possibility Racon stops after several rounds in any dataset?

**Comment by rvaser** [comment]
Racon should finish no matter which round it is. There is probably a bug somewhere :/

**Comment by rvaser** [comment]
Hmm, looking at the log it seems as the process prematurely finished without errors? What does the option `-m` of the `timeout` command do? Sets the number of maximal minutes?

**Comment by dcopetti** [comment]
hi,
it is the memory limit, I capped it at 600 GB. Over the whole run, Raven was using constantly just above 500 Gb in my case

**Comment by rvaser** [comment]
What is the default value for `timeout` to stop the running command?

**Comment by dcopetti** [comment]
I don't think there is a default value: this `timeout `command is not the Unix default:
https://github.com/pshved/timeout
http://coldattic.info/post/40/
and I wanted to use it just to cap the memory. I could do without it, now that I know the usage is stable. 
Do you think that that would have affected the output?

More in general, how do you print the assembly fasta file, and any other log/data that could be useful?

**Comment by rvaser** [comment]
I scrolled through the code of timeout and the default value for timelimit is not defined. I guess there might be something else that interrupted the run, not sure. You can save the log with `2> log.txt` and the fasta output with `> assembly.fasta` (see bellow). At this point nothing else is printable.

```bash
raven -t 20 Rabiosa_G303_all_10kb_q7heads.fa >rabiosa_10kb_raven_assembly 2> log.txt
```

**Comment by Tdanis** [comment]
> Racon should finish no matter which round it is. There is probably a bug somewhere :/

Hi again , so after choose  2 rounds of Racon, Raven worked properly.
But after 3 rounds of Racon, there is no fasta output.

**Comment by rvaser** [comment]
Were you able to find a smaller dataset on which it halts on the 3rd round?

**Comment by Tdanis** [comment]
Sorry for my late reply, but not yet I didnt find a smaller dataset.

**Comment by rvaser** [comment]
@Tdanis, I managed to fix the bug causing Raven to halt when three polishing rounds are used. You can test the latest commit on master branch or wait until the newest release is updated on bioconda.

Best regards,
Robert

**Comment by Tdanis** [comment]
Thank you very much for your response.

Theodoros Danis

________________________________
