### ISSUE TITLE
Is there a reference (preprint or publication) that can be cited for raven?

### ISSUE THREAD

**Issue by SchwarzEM** [lbcb-sci/raven#15]
I can find a bioRxiv preprint for the assembly program Ra:

https://doi.org/10.1101/656306

but not for raven.  Is there something out there?

**Comment by rvaser** [comment]
Hello Eric,
Ra has been published in a conference proceeding located [here](https://ieeexplore.ieee.org/document/8868909) (I will update the bioRxiv page), while Raven does not yet have a publication nor a preprint.

Best regards,
Robert

**Comment by SchwarzEM** [comment]
Thanks for the updated Ra reference!  I am looking forward to a Raven paper; in my hands, Raven has been outperforming other long-read assemblers (as measured by BUSCO scores of the resulting genome assemblies) and has been wonderfully easy to use (relatively low RAM and CPU-time requirements).
