### ISSUE TITLE
Circular contigs with Raven

### ISSUE THREAD

**Issue by vmurigneu** [lbcb-sci/raven#18]
Hi Robert,

I have a question about circular contigs for bacterial assembly please. Is there a way to distinguish between circular and linear contigs with Raven output. I tried to visualise the GFA file in Bandage but the contigs do not look circular. Contig self-alignment do not show evidence of overlapping ends.  I am planning to try the Circlator pipeline as well. 

Many thanks,
Valentine

**Comment by rvaser** [comment]
Hello Valentine,
the current version does not convey information about circularisation, and even if the contigs are circular, they are outputed as linear (no overlaps at their ends). I think I will have a working implementation by the end of this week.

Best regards,
Robert

**Comment by rvaser** [comment]
Implemented in the latest version `1.1.4` :)

**Comment by vmurigneu** [comment]
Hi Robert,

Thanks a lot.
I noticed a few small circular contigs (few kb) are present in the .gfa file (visualised using Bandage) but the fasta file only contains the chromosome and a large plasmid. Is there a way to retrieve the fasta sequence of those smaller plasmids please? Are they filter for some reasons in the assembly process?  In that case, we know there is at least one small 4 kb plasmid in the data and I can see a few circular contigs around that size in the .gfa. 

Thanks again for your help,
Valentine

**Comment by rvaser** [comment]
You can get all contigs from the GFA file with `awk '$1 ~/S/ {print ">"$2"\n"$3}' <gfa> > <fasta>`. Can you please run `grep ">" <fasta>` on the resulting file and paste the headers here? I usually filter out really small contigs, but might devise something for plasmids.

**Comment by vmurigneu** [comment]
Ok I was curious if there are some criteria apart from the size to filter out the contigs output in the fasta. 

So the headers of the new fasta containing all the contigs are:
>3240c93e-80f6-4d39-880b-45ac2869999d
>38b9a16e-fdab-4e37-8a33-736810ad142f
>Utg1714
>Ctg1716
>Utg1718
>Ctg1720
>Ctg1722
>Ctg1724
>Ctg1726
>Ctg1728
>Ctg1730
>Ctg1732
>Ctg1734
>Ctg1736
>Ctg1738
>Ctg1740

As compared to the original fasta:
>Utg1714 LN:i:135356 RC:i:11 XO:i:1
>Utg1718 LN:i:5103450 RC:i:680 XO:i:1

**Comment by rvaser** [comment]
Can you perhaps share the `raven.cereal` file so I can inspect locally?

**Comment by rvaser** [comment]
On second thought, you can just tell me which of the nodes has a circular edge, and find in the GFA file their length and read count (tags LN:i:<int> and RC:i:<int>, respectively).

**Comment by vmurigneu** [comment]
Those two contigs are circular:  
S	Ctg1716	LN:i:4023	RC:i:3
S	Ctg1732	LN:i:4085	RC:i:5

**Comment by mbhall88** [comment]
> the current version does not convey information about circularisation, and even if the contigs are circular, they are outputed as linear (no overlaps at their ends). I think I will have a working implementation by the end of this week.

> Implemented in the latest version `1.1.4` :)

Could this be documented somewhere? My understanding is that `XO:i:1` is circular and `XO:i:0` is linear (based on https://github.com/lbcb-sci/raven/blob/2c3d33740d04989062170ee6e241fb640071621c/RavenLib/src/common.cc#L245)?
