### ISSUE TITLE
raven.cereal

### ISSUE THREAD

**Issue by pmenzel** [lbcb-sci/raven#24]
Hi,

would it be possible to not create the file `raven.cereal` by default or delete it after raven is finished?

thanks,
Peter

**Comment by rvaser** [comment]
Available in the latest commit on master branch (`v1.2.0`), option `--disable-checkpoints`.

Sorry for the delay!
Best regards,
Robert

**Comment by pmenzel** [comment]
Thanks Robert!

Would you make a new release of v1.2.0 soon, so that this exciting new feature might hit bioconda eventually? ;)

best,
Peter

**Comment by rvaser** [comment]
Done! Sorry for the delay.
Best regards,
Robert

**Comment by pmenzel** [comment]
Thanks, got it now installed and it works!
