### ISSUE TITLE
Contigs and raw reads included in the GFA output

### ISSUE THREAD

**Issue by c-zhou** [lbcb-sci/raven#27]
Hello Robert,

I noticed that we have contigs and some raw reads included in the GFA output but not in the FASTA output (stdout). Also, it looks they are not polished by Racon. What is the point to include them? Which one should I use as the final genome assembly, the GFA or the FASTA?

Thanks,
Chenxi

**Comment by rvaser** [comment]
Hi Chenxi,
for the final assembly use the FASTA output. The GFA contains everything that has not been filtered out/resolved, while stuff we pass to Racon (and eventually output as FASTA) are only high confident contigs. For example, reads constituting unresolved tangles in the graph are not present in the FASTA, but are in the GFA for possible further processing. Hope this helps.

Best regards,
Robert

**Comment by c-zhou** [comment]
Cool, thanks Robert.
