### ISSUE TITLE
Assembly possibly getting stuck on mapping invalid reads

### ISSUE THREAD

**Issue by ASLeonard** [lbcb-sci/raven#29]
Hi Robert,
I've been running into some issues with assemblies not completing. It may be an issue with not giving the job enough time, but based on expectations and the logging, I'm not sure if it is an issue with the data or some loop.

I'm assembly a 2.8gb mammal genome with about 60x coverage. I've included the logging output below. Everything proceeds pretty quickly, until it gets "stuck" between minimising and mapping invalid reads. There is no further output after the first iteration of this loop until the job time expires. 

```
[raven::Graph::Construct] mapped sequences 978.772839s
[raven::Graph::Construct] minimized 3141332 - 3275448 / 5662746 16.137639s
[raven::Graph::Construct] mapped sequences 1060.586259s
[raven::Graph::Construct] minimized 3275448 - 3407851 / 5662746 16.112244s
...
[raven::Graph::Construct] mapped sequences 1794.347470s
[raven::Graph::Construct] minimized 5549681 - 5662746 / 5662746 12.567266s
[raven::Graph::Construct] mapped sequences 1453.411794s
[raven::Graph::Construct] annotated piles 56.984509s
[raven::Graph::Construct] removed contained sequences 40.598622s
[raven::Graph::Construct] removed chimeric sequences 136.707741s
[raven::Graph::Construct] reached checkpoint 89.431498s
[raven::Graph::Construct] cleared piles 1.909425s
[raven::Graph::Construct] minimized 0 - 48009 / 193871 19.858725s
```
After calling with `--resume`, the cereal file is reloaded, and then it appears to get stuck again on the first iteration of mapping invalid reads.

```
[raven::] loaded previous run 73.293433s
[raven::] loaded 5662746 sequences 2374.362824s
[raven::Graph::Construct] cleared piles 21.914438s
[raven::Graph::Construct] minimized 0 - 48009 / 193871 27.706757s
```
Both of these jobs expired after about 650 cpu hours each, compared to the 500 hours suggested for human scale at 44x.

I also tried with a separate dataset with about 30x coverage, but it was the same story of never getting beyond the first iteration of mapping invalid reads.

This was based on building from tip, but a conda-based install seems to be having the same issue  (stuck on the same spot after 400+ cpu hours).

Do you have any suggestions?

Thanks,
Alex

**Comment by rvaser** [comment]
Hi Alex,
mapping of valid and invalid reads together form a step and cereal files are created just before and after it, so reloading in the meantime will not help save on time. The huge amount of time needed for just the first step is ridiculous, there might be a bug. Did you check how many threads were running after it reaches this point? Would you be willing to share your data for future inspecting? Or can I paste some code modifications here so you can rerun it with `--resume`?

Best regards,
Robert

**Comment by ASLeonard** [comment]
Hi Robert,
There was some fluctuation, but typically around 22 cores were active (out of 36 requested), and memory was also fluctuating 400 +/- 20GB (around 400GB) with 540GB requested, so shouldn't be too near to swapping.

I can't share the data at this point, but can patch whatever modifications you have.

Thanks,
Alex

**Comment by rvaser** [comment]
Please add the following lines in graph.cpp and recompile:
590: `std::cerr << "Submitted sequences up to " << k << " " << timer.Lap() << "s" << std::endl;`
597: `std::cerr << "Mapped sequences " << timer.Lap() << "s" << std::endl;`
612: `std::cerr << "Updated piles " << timer.Lap() << "s" << std::endl;`
Rerun with --resume and when you get a couple of messages please paste them here.

**Comment by ASLeonard** [comment]
I've made the changes and recompiled. Just to check, I've put the change to line 612 *outside* the loop starting on line 610. (`for (const auto& it : void_futures)`).

These jobs have typically taken a day or two in the queue, so hopefully can update later this week.

**Comment by rvaser** [comment]
Yes, outside the loop. Thank you for testing!

**Comment by ASLeonard** [comment]
I ended up running the code on our shorter queue to get it done faster, so the job didn't finish as expected, but here is the output after the modifications.
```
[raven::Graph::Construct] minimized 0 - 37758 / 151430 20.154936s
Submitted sequences up to 183304 0.798463s
Mapped sequences 903.056223s
Updated piles 908.734677s
Submitted sequences up to 219957 920.057415s
Mapped sequences 1840.422080s
Updated piles 1845.854968s
Submitted sequences up to 253604 1856.707826s
Mapped sequences 2745.547218s
Updated piles 2750.923459s
Submitted sequences up to 287115 2761.236229s
Mapped sequences 3660.070341s
Updated piles 3664.163294s
Submitted sequences up to 318699 3674.392641s
Mapped sequences 4589.254558s
Updated piles 4593.274897s
Submitted sequences up to 349394 4603.464942s
Mapped sequences 5512.831154s
Updated piles 5517.166780s
Submitted sequences up to 382317 5526.881746s
Mapped sequences 6387.603507s
Updated piles 6391.894970s
Submitted sequences up to 413214 6401.957838s
Mapped sequences 7314.961789s
Updated piles 7319.386103s
Submitted sequences up to 444942 7329.574604s
Mapped sequences 8143.743216s
Updated piles 8147.232210s
Submitted sequences up to 474870 8156.080374s
Mapped sequences 9116.861529s
Updated piles 9122.813613s
Submitted sequences up to 506417 9133.849007s
Mapped sequences 10006.403595s
Updated piles 10011.889422s
Submitted sequences up to 538718 10021.413428s
Mapped sequences 10945.752363s
Updated piles 10951.041214s
Submitted sequences up to 569012 10960.498301s
Mapped sequences 11878.822528s
Updated piles 11884.348122s
Submitted sequences up to 600868 11894.510734s
```

I am guessing it shouldn't take that long to iterate through `thread_futures` between lines 590 and 597. Hopefully the 24h job will run soon and can see if there is any further information.

**Comment by rvaser** [comment]
Given the 900s trend for a 1Gb of sequences, the submited sequences up to 600868 should have finished by ~12800s. Is it still stuck at this point?

**Comment by ASLeonard** [comment]
The job was killed after 14,447 seconds. Approximately 1,400 seconds were used to reload cereal and load reads etc. It is close enough to be uncertain, but the last logging was as above, suggesting the submitted sequences didn't finish by 12,800 seconds, but would have needed > 13,000.

Hopefully the longer walltime job will run soon, and be more certain if the pattern continues or is broken.

**Comment by ASLeonard** [comment]
The pattern seems to continue, needing around 1,000 walltime seconds (~ 25,000 cpu seconds) per mapping chunk. These are the latest outputs.

```
Submitted sequences up to 2178615 61743.732448s
Mapped sequences 62697.638066s
Updated piles 62702.553917s
Submitted sequences up to 2215857 62713.817973s
Mapped sequences 63665.699476s
Updated piles 63670.002770s
Submitted sequences up to 2252661 63681.708879s
Mapped sequences 64692.900913s
Updated piles 64698.071899s
Submitted sequences up to 2288600 64710.338608s
```

This would imply it would take approximately 500 cpu hours to finish this loop, and then maybe 4x more to complete the rest of range in  the `raven::Graph::Construct] minimized 0 - 37758 / 151430`.

**Comment by rvaser** [comment]
That seems quite a bit for a mammalian genome. You can try and replace `0.00001` with `0.0001` at https://github.com/lbcb-sci/raven/blob/master/src/graph.cpp#L576.

**Comment by ASLeonard** [comment]
After changing that value, it now runs about 20x faster. Hopefully it'll be fine after this, but I'll post the logs once the 24h job gets running.

**Comment by ASLeonard** [comment]
It can reach the next checkpoint now (but ran out of memory, so re-running now). I guess there won't be a true reference for the impact on weakening the minimizer value to `0.0001`, but I'll report back with some stats once the assembly succeeds to evaluate.

**Comment by rvaser** [comment]
You should try the latest version (`1.3.0`), it uses a lot less memory.

**Comment by ASLeonard** [comment]
I switched to **1.3.0**, but now get the following error `[raven::Graph::Load] error: unable to load archive`. I get this error on when the checkpoint had reached a graph stage, as well as on a backup cereal file post read mapping. It may be some other issue caused by so many jobs starting/stopping, but I thought it might also be some issue now cereal looks to be a submodule of racon directly.

I'm restarting the run anyway, but thought I'd just report this anyway.

**Comment by rvaser** [comment]
Yes, this is expected because I have updated module cereal and some of the internal graph structures. Sorry for not mentioning this, I forgot it will not load the previous run.

**Comment by ASLeonard** [comment]
I have got back to the "remove tip and bubbles" stage, but this won't finish in the 4h queue with 36 cpus, so waiting for a 24h job to run.

It was running single-threaded for me, so maybe the node was IO bound by other jobs. When looking at the `removeTip` function, I didn't see any obvious threading, so maybe this stage is actually single-threaded? Either way, hopefully will make it through this stage soon. If not, I'll add some cerr output to check on the loop progression.

**Comment by rvaser** [comment]
Transitive, tip and bubble removal are all single threaded (and bubble removal can take a longer time to finish).

**Comment by ASLeonard** [comment]
I wasn't having any luck getting past the single-threaded step, so decided to upgrade to the latest version and give it one final try. I made the same change as recommended before

> That seems quite a bit for a mammalian genome. You can try and replace `0.00001` with `0.0001` at https://github.com/lbcb-sci/raven/blob/master/src/graph.cpp#L576.

and now the assembly finishes pretty quickly and with a **hugely** improvement memory footprint, compared to steps previously using over 850GB (7x improvement).

```
    CPU time :                                   1748996.88 sec.
    Max Memory :                                 118735 MB
    Average Memory :                             54135.41 MB
    Max Processes :                              3
    Max Threads :                                36
    Run time :                                   63026 sec.
```

I'm waiting to see if the runtime is still too slow without the weaker minimiser value, but I think this issue is now effectively resolved.

**Comment by rvaser** [comment]
Cool! Thanks for keeping me in the loop.

**Comment by ASLeonard** [comment]
With the standard minimiser value, the mapping of reads is still very slow, as initially reported. I'll stick with the weaker value.

Thanks for all your help!

**Comment by ASLeonard** [comment]
Just thought I'd update, with the latest code and no modifications, everything seems to go smoothly and as expected.

**Comment by rvaser** [comment]
Thank you for the update. I have replaced the invalid overlap step with a k-mer based annotation step. In addition, the bubble popping procedure had a similar problem when there are very repetitive sequences in the bubble, so I replaced minimizer based similarity with edit distance.
