### ISSUE TITLE
cannot find .fa.gz file

### ISSUE THREAD

**Issue by dcopetti** [lbcb-sci/raven#3]
Hello,
Just FYI: I was running raven with a compressed fasta file and I got this error:
[bioparser::createParser] error: unable to open file reads.fa.gz!
now, with a uncompressed input, it is running. I have raven v0.0.1

**Comment by rvaser** [comment]
Hello,
maybe you entered the wrong path to reads.fa.gz? I tried it now and compressed files should work.

Best regards,
Robert

**Comment by dcopetti** [comment]
...there was a typo in my command - sorry about that!
It is running well since a week or so now.
