### ISSUE TITLE
No FASTA output 

### ISSUE THREAD

**Issue by Daeap** [lbcb-sci/raven#30]
Hello Mr. Vaser, 

I tried out the Raven assembly (v1.3) for my assembly (2.3 Gbp) and ran it with this command: 

` raven -p 3 -t 30 <FASTQ.GZ>`

When it was completed it did not output me a FASTA file, instead I had to extract it out of my screenlog using grep,  as the sequences were written to the terminal. 

I am not sure why this happened, or if my assembly just crashed, but after examining the Screenlog, I could not find any error messages. When using the `--resume` option, it just prints the entire(?) sequence without headers again.

Cheers

David

**Comment by rvaser** [comment]
Hi David,
the assembly is outputted to stdout, so you have to pipe it like this `raven -p 3 -t 30 reads.fastq.gz > assembly.fa`. You can pipe it after the run as well by using --resume.

Best regards,
Robert

**Comment by Daeap** [comment]
Thank you. I'm very sorry I'm still new to Bioinformatics, thank you for your time!

Happy Holidays!

**Comment by rvaser** [comment]
No problem. Happy Holidays to you too:)

**Comment by antoine4ucsd** [comment]
Hello
Just reopening this issue because I have the same question...
I tried
```
raven -p 3 -t 30 input.fastq.gz > assembly.fa
```
but my output is empty. the only output I was able to get is the raven..cereal file.
How can I get a fasta output?
thank you +++
