### ISSUE TITLE
Estimate hardware requirements

### ISSUE THREAD

**Issue by aderzelle** [lbcb-sci/raven#31]
Hello,

do you have any benchmarks on the requirements of Raven in relation to the amount of data and the target genome size? 

I am wondering if I can assemble a 5 Gb (assembly size) genome on a powerful laptop. 

Thank you and keep safe.

**Comment by rvaser** [comment]
Hi,
the latest Raven version requires around 40% of the input FASTA file plus at most 16GB. How powerful is the laptop you are speaking of? What is the sequencing depth for the 5Gb genome?

Best regards,
Robert

**Comment by aderzelle** [comment]
It has 64 GB of ram and 8 threads. 

I don't know yet the sequencing depth as I did not receive the data yet. But it's a mollusc and my experience is that DNA extraction and sequencing is difficult with molluscs, so I am not expecting a super high coverage.

**Comment by rvaser** [comment]
Not sure if this will be sufficient memory.

**Comment by aderzelle** [comment]
I have had more info, the genome is a bit less than 2 Go. For the coverage itself, I will anyway remove the shortest reads, as this seems to help assemblers, so I can't tell the coverage before getting the data. I don't know if you saw that we benchmarked Ra and Raven, you might be interested as it seems Ra might outperform Raven in some conditions: 
[benchmark](https://doi.org/10.1101/2020.03.16.993428 )

**Comment by rvaser** [comment]
Given the smaller genome size, you might actually be able to assembly it on your laptop. I remember your benchmark, and you and Nadege helping me investigate the bug which increased the assembly size by much :)

**Comment by cement-head** [comment]
The answer is NO.  You cannot perform bioinformatics on a laptop - ever.  You must use machines with ECC RAM.
