### ISSUE TITLE
BUSCO

### ISSUE THREAD

**Issue by JParraV** [lbcb-sci/raven#32]
Hi. 
I have assembled the same set of PacBio reads using different assembler programs. When I analysed the assemblies' quality, I noticed that the BUSCO annotation is relatively low for Raven in particular, despite getting similar contiguity that others assemblers such as Flye. Any idea why this is going on?
Thank you.

![image](https://user-images.githubusercontent.com/69057776/105556870-d5031980-5d02-11eb-9b3d-0b17c4098a78.png)

**Comment by rvaser** [comment]
Hello,
Raven probably has more indels on this datasets than other assemblers. For some PacBio datasets we have seen such behaviour before. You can try and polish Raven assembly with any other tool and see if that is true.

Best regards,
Robert

**Comment by JParraV** [comment]
Hello,
That makes sense. I ran QUAST aligning them to the Illumina-based assembly (with Unicycler) as the reference genome, and you're right. Thanks for your time!
