### ISSUE TITLE
Does raven use the extra information in fastq file?

### ISSUE THREAD

**Issue by aderzelle** [lbcb-sci/raven#33]
Hello,

I am currently switching to genomics of organisms that have considerably big genomes. Therefore the question of data storage space becomes prominent. I was wondering if Raven was using the extra information relative to base quality in the fastq or if I could just convert my fastq to fasta, if Raven doesn't care about fastq. 

Thank you

EDIT: I was also wondering if you planned a publication, or at least somewhere with more in depth description of how raven does work computationally.

**Comment by rvaser** [comment]
Hello,
quality values are only used for polishing with Racon, and if you omit them you should expect lower base accuracy. If you are worrying about RAM usage, quality values constitute a tiny portion of Raven's requirements.

Raven preprint can be fount here: https://doi.org/10.1101/2020.08.07.242461.

Best regards,
Robert

**Comment by aderzelle** [comment]
Ok, so anyway remapping the fastq and calling Racon should help if I used the fasta as starting point.

Thanks for the preprint link!
