### ISSUE TITLE
How to cite raven?

### ISSUE THREAD

**Issue by linsalrob** [lbcb-sci/raven#34]
Is there a citation for Raven and can you add it to the Readme?

Thanks

Rob

**Comment by rvaser** [comment]
Hi Rob,
the citation is https://www.biorxiv.org/content/10.1101/2020.08.07.242461v1. It is already present in the README.md, at the top there is a git shield: [![Preprint at bioRxiv](https://img.shields.io/badge/preprint-bioRxiv-orange)](https://doi.org/10.1101/2020.08.07.242461).

Best regards,
Robert

**Comment by linsalrob** [comment]
Awesome, sorry I missed it!

**Comment by blaiseli** [comment]
For what its worth, I also missed the "git shield" about citing. That's why I searched in the issues and am currently commenting this one.

In my opinion, it would help having also a plain section about citing around the end of the README.md
