### ISSUE TITLE
How to use multiple fastq files?

### ISSUE THREAD

**Issue by Ural-Yunusbaev** [lbcb-sci/raven#38]
How to use multiple fastq files?
Can I use: 
raven lib1.fq lib2.fq > assembly.fa

**Comment by rvaser** [comment]
Hi Ural,
Unfortunately no, but I can add this functionality if you want.

Best regards,
Robert

**Comment by Ural-Yunusbaev** [comment]
I tryed the command
raven lib1.fq lib2.fq > assembly.fa
It works. how does it possible?

**Comment by Ural-Yunusbaev** [comment]
May bee it uses only one of the libs?
It would be great if you add this functionality. How long it will take?
Thank you in advance.

Best regards,
Ural

**Comment by rvaser** [comment]
The current version will only parse the first floating argument, ignoring everything afterwards.

**Comment by Ural-Yunusbaev** [comment]
Can I do this:
cat lib1.fq lib2.fq > lib1_2.fq
raven lib1_2.fq > assembly.fa
?

**Comment by rvaser** [comment]
Yes you can, as long as everything is in one file it will work.

**Comment by Ural-Yunusbaev** [comment]
Thank you!

**Comment by ctxchris** [comment]
For me `raven lib*.fasta `worked, all input file were used.

**Comment by rvaser** [comment]
I finally enabled multiple files as input in commit bfd5f9e (v1.5.2).
