### ISSUE TITLE
Racon settings after Raven assembly

### ISSUE THREAD

**Issue by michieitel** [lbcb-sci/raven#4]
Dear Robert,

I would like to run Medaka after Raven. ONT suggest to run 1 round of Racon polishing before starting with the Medaka polishing and they suggest specific setting for the Racon stage. 
ONT suggests to run Racon with: 
`racon -m 8 -x -6 -g -8 -w 500 …`

Is there a way to add the possibility to change the Racon setting during the Raven run?

Where any specific Racon settings hardcoded in Raven or does it currently use defaults?

I do not want to run Racon through the normal Raven pipeline and then again with different settings. This might not be helpful to yield the best consensus in the end.
Thanks for your help!

Michael

**Comment by rvaser** [comment]
Hi Michael,
the default parameters of Racon have been changed to `-m 3 -x -5 -g -4 -w 500` and are used in Raven as well. You can set the number of desired Racon rounds in Raven with parameter `-p <int>`. If it is set to 0, you can manually run Racon later. Or you can change the parameters in Raven directly [here](https://github.com/lbcb-sci/raven/blob/master/src/main.cpp#L136) and compile afterwards (and use `-p 1` to apply only 1 iteration).

Sorry for the wait.
Best regards,
Robert

**Comment by michieitel** [comment]
Great. Thanks for the tip.

Best
Michael
