### ISSUE TITLE
Shorter segments than overlaps in GFA

### ISSUE THREAD

**Issue by AntoineHo** [lbcb-sci/raven#45]
Hello,

While looking at the GFA output of raven, I noticed that some links have longer overlaps than the segment size allows. For instance:

```bash
S  ch227_read12486_template_pass_FAH31515     LN:i:15968       RC:i:1
S  ch96_read20376_template_pass_FAH42885      LN:i:5840        RC:i:1
L  ch227_read12486_template_pass_FAH31515     ch96_read20376_template_pass_FAH42885       -       6422M
```

Is this expected?

Cheers

**Comment by rvaser** [comment]
Hi,
it is probably due to indels as the overlap is calculated via minimizers and not alignment. You can send me the `raven.cereal` file so we can be sure.

Best regards,
Robert

**Comment by AntoineHo** [comment]
Thank you for your quick reply, here is the file: https://we.tl/t-o5kc0TBYQJ

Best regards,
Antoine

**Comment by rvaser** [comment]
Seems alright to me, the edge pair has overlap of length 5816.

**Comment by AntoineHo** [comment]
Ok, so the reported overlap in the GFA is overestimated. I wanted to merge some paths in the graph but I will simply ignore these links where segment length is smaller than reported overlaps.

**Comment by rvaser** [comment]
The safest thing to do is find suffix-prefix overlaps for given links and join accordingly.

**Comment by AntoineHo** [comment]
Ok, thanks, I will realign the segments from links where the overlap is larger.
