### ISSUE TITLE
No fasta output 

### ISSUE THREAD

**Issue by mgantz** [lbcb-sci/raven#47]
Hi! 

I am trying to polish a set of nanopore amplicon sequences from a very small gene but the following command just gives me an empty file as output: 

raven cluster_1.fasta > 1.fasta

This is what is printed in my terminal: 

[raven::] loaded 42 sequences 0.004137s
[raven::Graph::Construct] minimized 0 - 42 / 42 0.024922s
[raven::Graph::Construct] mapped sequences 0.005538s
[raven::Graph::Construct] annotated piles 0.000533s
[raven::Graph::Construct] removed contained sequences 0.000017s
[raven::Graph::Construct] removed chimeric sequences 0.000060s
[raven::Graph::Construct] reached checkpoint 0.000276s
[raven::Graph::Construct] minimized 0 - 4 / 4 0.017390s
[raven::Graph::Construct] mapped valid sequences 0.000413s
[raven::Graph::Construct] updated overlaps 0.000002s
[raven::Graph::Construct] removed false overlaps 0.000047s
[raven::Graph::Construct] stored 8 nodes 0.000061s
[raven::Graph::Construct] stored 12 edges 0.000007s
[raven::Graph::Construct] reached checkpoint 0.000337s
[raven::Graph::Construct] 0.049604s
[raven::Graph::Assemble] removed transitive edges 0.000027s
[raven::Graph::Assemble] reached checkpoint 0.000200s
[raven::Graph::Assemble] removed tips and bubbles 0.000005s
[raven::Graph::Assemble] reached checkpoint 0.000223s
[raven::Graph::Assemble] removed long edges 0.000061s
[raven::Graph::Assemble] reached checkpoint 0.000146s
[raven::Graph::Assemble] 0.000712s
[raven::] 0.056928s

It seems, raven stops processing after assembly. Is there any way to resolve this issue?

**Comment by rvaser** [comment]
Hello,
how long are the amplicons? Do they need assembling or just polishing? If the latter, you can use [Racon](https://github.com/lbcb-sci/racon) instead.

Best regards,
Robert

**Comment by mgantz** [comment]
Thank you for the quick response! 

The amplicons are 1 - 2 kb long and I just need consensus generation. 

Thank you for the suggestions. I tried to use racon in the first place but ran into the problem that it gives me a .fasta file with multiple sequences as consensus which are quite similar when I align them and which I would expect to form a consensus sequence. That's how I run racon:

minimap2 -x ava-ont cluster_49.fasta cluster_49.fasta > aln.paf

racon cluster_49.fasta aln.paf cluster_49.fasta > racon_49x49.fasta

Usually I would use a reference (which always gives me a single consensus sequence) but that is not possible here as I don't know the genes well enough to define a reference (which is why I tried out raven). Could it be that there is a problem with the alignment mode?

**Comment by rvaser** [comment]
If you want to polish all sequences, you need option `-f` in racon (otherwise it will retain only one overlap per sequence). If you want one consensus sequence, you can choose one sequence randomly from your file as the backbone and run racon with it. Or easier, you can create a consensus/MSA with [spoa](https://github.com/rvaser/spoa) directly.

**Comment by mgantz** [comment]
Thank you! Both, picking one random sequence as backbone and using spoa worked perfectly fine.
