### ISSUE TITLE
Transport selection via DSN is deprecated

### ISSUE THREAD

**Issue by domivika** [lbcb-sci/raven#48]
Hello,

Since the last version update (1.5.1) the error I get is:

"Transport selection via DSN is deprecated. You should explicitly pass the transport class to Client() instead."

The job runs only when older version is used.

**Comment by rvaser** [comment]
Hi,
I am not sure if you got the right repository, this one is a de novo genome assembler.

Best regards,
Robert

**Comment by domivika** [comment]
Of course. Sorry. I wanted to use your assembler but used the wrong name when creating env through conda. Feel free to delete this issue.
