### ISSUE TITLE
different results running the same dataset 3 times

### ISSUE THREAD

**Issue by michieitel** [lbcb-sci/raven#5]
Hi!

I just encountered that when running Raven three times with the same settings on the same ONT dataset I get different results. Is that expected with the used algorithm?

I was running raven 3 times each on three datasets (all reads >1kb, all >5kb, all >10kb). 
The expected coverage of the three datasets were:
- 1kb+: ~110x
- 5kb+: ~80
- 10kb+: ~40x

I used these commands:
```
# RAVEN_run1_1kb:
raven -t 20 -p 0 reads_porechopped.1kb.combined.fastq.gz > RAVEN_run1_1kb.fasta 2> RAVEN_run1_1kb.log

# RAVEN_run2_1kb:
raven -t 20 -p 0 reads_porechopped.1kb.combined.fastq.gz > RAVEN_run2_1kb.fasta 2> RAVEN_run2_1kb.log

# RAVEN_run3_1kb:
raven -t 20 -p 0 reads_porechopped.1kb.combined.fastq.gz > RAVEN_run3_1kb.fasta 2> RAVEN_run3_1kb.log

# RAVEN_run1_5kb:
raven -t 20 -p 0 reads_porechopped.5kb.fasta.gz > RAVEN_run1_5kb.fasta 2> RAVEN_run1_5kb.log

# RAVEN_run2_5kb:
raven -t 20 -p 0 reads_porechopped.5kb.fasta.gz > RAVEN_run2_5kb.fasta 2> RAVEN_run2_5kb.log

# RAVEN_run3_5kb:
raven -t 20 -p 0 reads_porechopped.5kb.fasta.gz > RAVEN_run3_5kb.fasta 2> RAVEN_run3_5kb.log

# RAVEN_run1_10kb:
raven -t 20 -p 0 reads_porechopped.10kb.fasta.gz > RAVEN_run1_10kb.fasta 2> RAVEN_run1_10kb.log

# RAVEN_run2_10kb:
raven -t 20 -p 0 reads_porechopped.10kb.fasta.gz > RAVEN_run2_10kb.fasta 2> RAVEN_run2_10kb.log

# RAVEN_run3_10kb:
raven -t 20 -p 0 reads_porechopped.10kb.fasta.gz > RAVEN_run3_10kb.fasta 2> RAVEN_run3_10kb.log
```

The stats of the raw (unpolished) assemblies are as follows:
![RAVEN_stats](https://user-images.githubusercontent.com/12069446/66034607-d86d0300-e509-11e9-84a6-e4515c0851dc.png)

As you can see the stats are generally comparable between the runs for each dataset. However, what is quite striking is the huge difference between the longest contigs that were generated.

Any clue as to why this happens and how one can be sure one gets the best possible assembly?

Thanks
Michael

**Comment by rvaser** [comment]
Hi Michael,
yes, this behavior is expected because the final heuristic places the graph in a 2d plane starting from a **random** initial layout. To increase the chance of good drawings that enable the detection of false edges, we restart the whole process several times. I have increased that number in the latest commit, although there is no guarantee that this will prevent different assembly results. Thanks for the evaluation!

Best regards,
Robert

**Comment by michieitel** [comment]
Dear Robert,
great. Good to know and thanks for the fast update. I will run the test again with the latest commit and see if the outputs are closer now. I understand that there is some variability, but 30% in the longest contig seems too much...

Best,
Michael

**Comment by rvaser** [comment]
Yeah well, the edge that is either removed or not is probably in the middle of the longest contig. We are considering to create a set of random seeds which will remove the nondeterministic behaviour. Will get back to you.

Best regards,
Robert

**Comment by rvaser** [comment]
I pushed a patch with fixed random seeds (`v0.03`) which should now yield the same output always.

**Comment by michieitel** [comment]
Cool Thanks. I will give it try again.

cheers
Micahel

**Comment by michieitel** [comment]
btw - the Ra assembler yielded the same output for repetitions ;-)

**Comment by rvaser** [comment]
That is because it did not have this additional heuristic at end :)

**Comment by rvaser** [comment]
@michieitel, do you mind if I close this issue as random seeds have been dealt with?

**Comment by michieitel** [comment]
sure. I worked great now! thanks for your help!
