### ISSUE TITLE
What are the other steps we should follow after raven assembly?

### ISSUE THREAD

**Issue by thulasis** [lbcb-sci/raven#61]
Hi I am using nanopore data for assembly. It is rapid and computationally stable. Do you recommend other polishing methods like medaka after raven? I am getting some single contigs for genome assemblies but unable to circularize the genome. Do you suggest anything to solve this issue? I am using latest 1.8.1 version. 

Is it possible to run raven with reference genome?

Thanks in advance,
Tulasi

**Comment by rvaser** [comment]
Hi Tulasi,
you can run medaka to polish the assembly further. For circularization you can try https://github.com/sanger-pathogens/circlator. For reference based assembly you can try https://github.com/rrwick/Rebaler.

Best regards,
Robert

**Comment by thulasis** [comment]
> Hi Tulasi, you can run medaka to polish the assembly further. For circularization you can try https://github.com/sanger-pathogens/circlator. For reference based assembly you can try https://github.com/rrwick/Rebaler.
> 
> Best regards, Robert

Hi Robert,

Thank you for your suggestion. I did some k-mer optimizations while running the rave and finally got the circular genome maps. 
I will definitely look at the rebaler for the reference based assembly. I will use medaka for the polishing. 

Thanks again.

Best,
Tulasi
