### ISSUE TITLE
Nanopore Q20 Data

### ISSUE THREAD

**Issue by gwl2** [lbcb-sci/raven#67]
Are there any adjustments that I have to make for Nanopore Q20 data?
I saw that there is an option for Flye (nano-hq) and was wondering if there is something similar for Raven.

**Comment by tbrekalo** [comment]
None at the moment :)

**Comment by gwl2** [comment]
I just gave it a try, no special adjustments needed, performs already pretty close to Flye with nano-hq.
Get in touch if you need more info or test data.

**Comment by tbrekalo** [comment]
Thanks. :) 

Apologies for the late follow up.
