### ISSUE TITLE
How could we get the gfa assemble result

### ISSUE THREAD

**Issue by ld9866** [lbcb-sci/raven#80]
Dear developer:
We are assembling the genome using raven, but we found that we are having a hard time getting the file in gfa format and there is no such example in the sample file, can you help me?
The example coud for fasta: （works well）
raven --threads 100 sample.fastq.gz > sample.raven.contigs.fasta 
but what we want is to get the gfa assemble result ,how could we solve this?

**Comment by FilipTomas** [comment]
Hi, 
To output a gfa file, use the -F or --graphical-fragment-assembly option. Both options perform the same functionality, with the former being a shorter alternative to write.
E.g. raven --threads 100 -F sample.raven.gfa  sample.fastq.gz > sample.raven.contigs.fasta
Hope this answers your question.

**Comment by ld9866** [comment]
Thank you! we have done this with your help!
